# quay.io/boundlessgeo/bex-nodejs-bower-grunt
# docker build -t bex-nodejs-bower-grunt .
FROM node:9.4.0-stretch
LABEL maintainer="Daniel Berry <dberry@boundlessgeo.com>"

RUN npm install -g bower grunt-cli karma

CMD ["/bin/bash"]
